// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: secrets.proto

package gophkeeper

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SecretInfo_Kind int32

const (
	SecretInfo_UNDEFINED   SecretInfo_Kind = 0
	SecretInfo_CREDENTIALS SecretInfo_Kind = 1
	SecretInfo_CARD        SecretInfo_Kind = 2
	SecretInfo_TEXT        SecretInfo_Kind = 3
	SecretInfo_RAW         SecretInfo_Kind = 4
)

// Enum value maps for SecretInfo_Kind.
var (
	SecretInfo_Kind_name = map[int32]string{
		0: "UNDEFINED",
		1: "CREDENTIALS",
		2: "CARD",
		3: "TEXT",
		4: "RAW",
	}
	SecretInfo_Kind_value = map[string]int32{
		"UNDEFINED":   0,
		"CREDENTIALS": 1,
		"CARD":        2,
		"TEXT":        3,
		"RAW":         4,
	}
)

func (x SecretInfo_Kind) Enum() *SecretInfo_Kind {
	p := new(SecretInfo_Kind)
	*p = x
	return p
}

func (x SecretInfo_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecretInfo_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_secrets_proto_enumTypes[0].Descriptor()
}

func (SecretInfo_Kind) Type() protoreflect.EnumType {
	return &file_secrets_proto_enumTypes[0]
}

func (x SecretInfo_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SecretInfo_Kind.Descriptor instead.
func (SecretInfo_Kind) EnumDescriptor() ([]byte, []int) {
	return file_secrets_proto_rawDescGZIP(), []int{0, 0}
}

type SecretInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          [][]byte               `protobuf:"bytes,1,rep,name=uuid,proto3" json:"uuid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Kind          SecretInfo_Kind        `protobuf:"varint,3,opt,name=kind,proto3,enum=gophkeeper.SecretInfo_Kind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretInfo) Reset() {
	*x = SecretInfo{}
	mi := &file_secrets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretInfo) ProtoMessage() {}

func (x *SecretInfo) ProtoReflect() protoreflect.Message {
	mi := &file_secrets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretInfo.ProtoReflect.Descriptor instead.
func (*SecretInfo) Descriptor() ([]byte, []int) {
	return file_secrets_proto_rawDescGZIP(), []int{0}
}

func (x *SecretInfo) GetUuid() [][]byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *SecretInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SecretInfo) GetKind() SecretInfo_Kind {
	if x != nil {
		return x.Kind
	}
	return SecretInfo_UNDEFINED
}

type Credentials struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Credentials) Reset() {
	*x = Credentials{}
	mi := &file_secrets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credentials) ProtoMessage() {}

func (x *Credentials) ProtoReflect() protoreflect.Message {
	mi := &file_secrets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credentials.ProtoReflect.Descriptor instead.
func (*Credentials) Descriptor() ([]byte, []int) {
	return file_secrets_proto_rawDescGZIP(), []int{1}
}

func (x *Credentials) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *Credentials) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type Card struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Number           string                 `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Holder           string                 `protobuf:"bytes,2,opt,name=holder,proto3" json:"holder,omitempty"`
	Expires          string                 `protobuf:"bytes,3,opt,name=expires,proto3" json:"expires,omitempty"`
	VerificationCode string                 `protobuf:"bytes,4,opt,name=verification_code,json=verificationCode,proto3" json:"verification_code,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_secrets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_secrets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_secrets_proto_rawDescGZIP(), []int{2}
}

func (x *Card) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Card) GetHolder() string {
	if x != nil {
		return x.Holder
	}
	return ""
}

func (x *Card) GetExpires() string {
	if x != nil {
		return x.Expires
	}
	return ""
}

func (x *Card) GetVerificationCode() string {
	if x != nil {
		return x.VerificationCode
	}
	return ""
}

type Text struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Text) Reset() {
	*x = Text{}
	mi := &file_secrets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Text) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Text) ProtoMessage() {}

func (x *Text) ProtoReflect() protoreflect.Message {
	mi := &file_secrets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Text.ProtoReflect.Descriptor instead.
func (*Text) Descriptor() ([]byte, []int) {
	return file_secrets_proto_rawDescGZIP(), []int{3}
}

func (x *Text) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type Raw struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Raw) Reset() {
	*x = Raw{}
	mi := &file_secrets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Raw) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Raw) ProtoMessage() {}

func (x *Raw) ProtoReflect() protoreflect.Message {
	mi := &file_secrets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Raw.ProtoReflect.Descriptor instead.
func (*Raw) Descriptor() ([]byte, []int) {
	return file_secrets_proto_rawDescGZIP(), []int{4}
}

func (x *Raw) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type Secret struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Types that are valid to be assigned to Secret:
	//
	//	*Secret_Credentials
	//	*Secret_Card
	//	*Secret_Text
	//	*Secret_Raw
	Secret        isSecret_Secret `protobuf_oneof:"secret"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Secret) Reset() {
	*x = Secret{}
	mi := &file_secrets_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Secret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secret) ProtoMessage() {}

func (x *Secret) ProtoReflect() protoreflect.Message {
	mi := &file_secrets_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secret.ProtoReflect.Descriptor instead.
func (*Secret) Descriptor() ([]byte, []int) {
	return file_secrets_proto_rawDescGZIP(), []int{5}
}

func (x *Secret) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Secret) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Secret) GetSecret() isSecret_Secret {
	if x != nil {
		return x.Secret
	}
	return nil
}

func (x *Secret) GetCredentials() *Credentials {
	if x != nil {
		if x, ok := x.Secret.(*Secret_Credentials); ok {
			return x.Credentials
		}
	}
	return nil
}

func (x *Secret) GetCard() *Card {
	if x != nil {
		if x, ok := x.Secret.(*Secret_Card); ok {
			return x.Card
		}
	}
	return nil
}

func (x *Secret) GetText() *Text {
	if x != nil {
		if x, ok := x.Secret.(*Secret_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *Secret) GetRaw() *Raw {
	if x != nil {
		if x, ok := x.Secret.(*Secret_Raw); ok {
			return x.Raw
		}
	}
	return nil
}

type isSecret_Secret interface {
	isSecret_Secret()
}

type Secret_Credentials struct {
	Credentials *Credentials `protobuf:"bytes,4,opt,name=credentials,proto3,oneof"`
}

type Secret_Card struct {
	Card *Card `protobuf:"bytes,5,opt,name=card,proto3,oneof"`
}

type Secret_Text struct {
	Text *Text `protobuf:"bytes,6,opt,name=text,proto3,oneof"`
}

type Secret_Raw struct {
	Raw *Raw `protobuf:"bytes,7,opt,name=raw,proto3,oneof"`
}

func (*Secret_Credentials) isSecret_Secret() {}

func (*Secret_Card) isSecret_Secret() {}

func (*Secret_Text) isSecret_Secret() {}

func (*Secret_Raw) isSecret_Secret() {}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_secrets_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secrets_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_secrets_proto_rawDescGZIP(), []int{6}
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretsInfo   []*SecretInfo          `protobuf:"bytes,1,rep,name=secrets_info,json=secretsInfo,proto3" json:"secrets_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_secrets_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secrets_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_secrets_proto_rawDescGZIP(), []int{7}
}

func (x *ListResponse) GetSecretsInfo() []*SecretInfo {
	if x != nil {
		return x.SecretsInfo
	}
	return nil
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        *Secret                `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_secrets_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secrets_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_secrets_proto_rawDescGZIP(), []int{8}
}

func (x *CreateRequest) GetSecret() *Secret {
	if x != nil {
		return x.Secret
	}
	return nil
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          [][]byte               `protobuf:"bytes,1,rep,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_secrets_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secrets_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_secrets_proto_rawDescGZIP(), []int{9}
}

func (x *CreateResponse) GetUuid() [][]byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

type ReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          [][]byte               `protobuf:"bytes,1,rep,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_secrets_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secrets_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_secrets_proto_rawDescGZIP(), []int{10}
}

func (x *ReadRequest) GetUuid() [][]byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

type ReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        *Secret                `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_secrets_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secrets_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_secrets_proto_rawDescGZIP(), []int{11}
}

func (x *ReadResponse) GetSecret() *Secret {
	if x != nil {
		return x.Secret
	}
	return nil
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          [][]byte               `protobuf:"bytes,1,rep,name=uuid,proto3" json:"uuid,omitempty"`
	Secret        *Secret                `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_secrets_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secrets_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_secrets_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateRequest) GetUuid() [][]byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *UpdateRequest) GetSecret() *Secret {
	if x != nil {
		return x.Secret
	}
	return nil
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_secrets_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secrets_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_secrets_proto_rawDescGZIP(), []int{13}
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          [][]byte               `protobuf:"bytes,1,rep,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_secrets_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secrets_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_secrets_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteRequest) GetUuid() [][]byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_secrets_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secrets_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_secrets_proto_rawDescGZIP(), []int{15}
}

var File_secrets_proto protoreflect.FileDescriptor

const file_secrets_proto_rawDesc = "" +
	"\n" +
	"\rsecrets.proto\x12\n" +
	"gophkeeper\"\xaa\x01\n" +
	"\n" +
	"SecretInfo\x12\x12\n" +
	"\x04uuid\x18\x01 \x03(\fR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12/\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x1b.gophkeeper.SecretInfo.KindR\x04kind\"C\n" +
	"\x04Kind\x12\r\n" +
	"\tUNDEFINED\x10\x00\x12\x0f\n" +
	"\vCREDENTIALS\x10\x01\x12\b\n" +
	"\x04CARD\x10\x02\x12\b\n" +
	"\x04TEXT\x10\x03\x12\a\n" +
	"\x03RAW\x10\x04\"?\n" +
	"\vCredentials\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"}\n" +
	"\x04Card\x12\x16\n" +
	"\x06number\x18\x01 \x01(\tR\x06number\x12\x16\n" +
	"\x06holder\x18\x02 \x01(\tR\x06holder\x12\x18\n" +
	"\aexpires\x18\x03 \x01(\tR\aexpires\x12+\n" +
	"\x11verification_code\x18\x04 \x01(\tR\x10verificationCode\" \n" +
	"\x04Text\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"\x1f\n" +
	"\x03Raw\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\"\xfa\x01\n" +
	"\x06Secret\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12;\n" +
	"\vcredentials\x18\x04 \x01(\v2\x17.gophkeeper.CredentialsH\x00R\vcredentials\x12&\n" +
	"\x04card\x18\x05 \x01(\v2\x10.gophkeeper.CardH\x00R\x04card\x12&\n" +
	"\x04text\x18\x06 \x01(\v2\x10.gophkeeper.TextH\x00R\x04text\x12#\n" +
	"\x03raw\x18\a \x01(\v2\x0f.gophkeeper.RawH\x00R\x03rawB\b\n" +
	"\x06secret\"\r\n" +
	"\vListRequest\"I\n" +
	"\fListResponse\x129\n" +
	"\fsecrets_info\x18\x01 \x03(\v2\x16.gophkeeper.SecretInfoR\vsecretsInfo\";\n" +
	"\rCreateRequest\x12*\n" +
	"\x06secret\x18\x01 \x01(\v2\x12.gophkeeper.SecretR\x06secret\"$\n" +
	"\x0eCreateResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x03(\fR\x04uuid\"!\n" +
	"\vReadRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x03(\fR\x04uuid\":\n" +
	"\fReadResponse\x12*\n" +
	"\x06secret\x18\x01 \x01(\v2\x12.gophkeeper.SecretR\x06secret\"O\n" +
	"\rUpdateRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x03(\fR\x04uuid\x12*\n" +
	"\x06secret\x18\x02 \x01(\v2\x12.gophkeeper.SecretR\x06secret\"\x10\n" +
	"\x0eUpdateResponse\"#\n" +
	"\rDeleteRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x03(\fR\x04uuid\"\x10\n" +
	"\x0eDeleteResponse2\xc2\x02\n" +
	"\aSecrets\x129\n" +
	"\x04List\x12\x17.gophkeeper.ListRequest\x1a\x18.gophkeeper.ListResponse\x12?\n" +
	"\x06Create\x12\x19.gophkeeper.CreateRequest\x1a\x1a.gophkeeper.CreateResponse\x129\n" +
	"\x04Read\x12\x17.gophkeeper.ReadRequest\x1a\x18.gophkeeper.ReadResponse\x12?\n" +
	"\x06Update\x12\x19.gophkeeper.UpdateRequest\x1a\x1a.gophkeeper.UpdateResponse\x12?\n" +
	"\x06Delete\x12\x19.gophkeeper.DeleteRequest\x1a\x1a.gophkeeper.DeleteResponseB\x0eZ\f./gophkeeperb\x06proto3"

var (
	file_secrets_proto_rawDescOnce sync.Once
	file_secrets_proto_rawDescData []byte
)

func file_secrets_proto_rawDescGZIP() []byte {
	file_secrets_proto_rawDescOnce.Do(func() {
		file_secrets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_secrets_proto_rawDesc), len(file_secrets_proto_rawDesc)))
	})
	return file_secrets_proto_rawDescData
}

var file_secrets_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_secrets_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_secrets_proto_goTypes = []any{
	(SecretInfo_Kind)(0),   // 0: gophkeeper.SecretInfo.Kind
	(*SecretInfo)(nil),     // 1: gophkeeper.SecretInfo
	(*Credentials)(nil),    // 2: gophkeeper.Credentials
	(*Card)(nil),           // 3: gophkeeper.Card
	(*Text)(nil),           // 4: gophkeeper.Text
	(*Raw)(nil),            // 5: gophkeeper.Raw
	(*Secret)(nil),         // 6: gophkeeper.Secret
	(*ListRequest)(nil),    // 7: gophkeeper.ListRequest
	(*ListResponse)(nil),   // 8: gophkeeper.ListResponse
	(*CreateRequest)(nil),  // 9: gophkeeper.CreateRequest
	(*CreateResponse)(nil), // 10: gophkeeper.CreateResponse
	(*ReadRequest)(nil),    // 11: gophkeeper.ReadRequest
	(*ReadResponse)(nil),   // 12: gophkeeper.ReadResponse
	(*UpdateRequest)(nil),  // 13: gophkeeper.UpdateRequest
	(*UpdateResponse)(nil), // 14: gophkeeper.UpdateResponse
	(*DeleteRequest)(nil),  // 15: gophkeeper.DeleteRequest
	(*DeleteResponse)(nil), // 16: gophkeeper.DeleteResponse
}
var file_secrets_proto_depIdxs = []int32{
	0,  // 0: gophkeeper.SecretInfo.kind:type_name -> gophkeeper.SecretInfo.Kind
	2,  // 1: gophkeeper.Secret.credentials:type_name -> gophkeeper.Credentials
	3,  // 2: gophkeeper.Secret.card:type_name -> gophkeeper.Card
	4,  // 3: gophkeeper.Secret.text:type_name -> gophkeeper.Text
	5,  // 4: gophkeeper.Secret.raw:type_name -> gophkeeper.Raw
	1,  // 5: gophkeeper.ListResponse.secrets_info:type_name -> gophkeeper.SecretInfo
	6,  // 6: gophkeeper.CreateRequest.secret:type_name -> gophkeeper.Secret
	6,  // 7: gophkeeper.ReadResponse.secret:type_name -> gophkeeper.Secret
	6,  // 8: gophkeeper.UpdateRequest.secret:type_name -> gophkeeper.Secret
	7,  // 9: gophkeeper.Secrets.List:input_type -> gophkeeper.ListRequest
	9,  // 10: gophkeeper.Secrets.Create:input_type -> gophkeeper.CreateRequest
	11, // 11: gophkeeper.Secrets.Read:input_type -> gophkeeper.ReadRequest
	13, // 12: gophkeeper.Secrets.Update:input_type -> gophkeeper.UpdateRequest
	15, // 13: gophkeeper.Secrets.Delete:input_type -> gophkeeper.DeleteRequest
	8,  // 14: gophkeeper.Secrets.List:output_type -> gophkeeper.ListResponse
	10, // 15: gophkeeper.Secrets.Create:output_type -> gophkeeper.CreateResponse
	12, // 16: gophkeeper.Secrets.Read:output_type -> gophkeeper.ReadResponse
	14, // 17: gophkeeper.Secrets.Update:output_type -> gophkeeper.UpdateResponse
	16, // 18: gophkeeper.Secrets.Delete:output_type -> gophkeeper.DeleteResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_secrets_proto_init() }
func file_secrets_proto_init() {
	if File_secrets_proto != nil {
		return
	}
	file_secrets_proto_msgTypes[5].OneofWrappers = []any{
		(*Secret_Credentials)(nil),
		(*Secret_Card)(nil),
		(*Secret_Text)(nil),
		(*Secret_Raw)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_secrets_proto_rawDesc), len(file_secrets_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_secrets_proto_goTypes,
		DependencyIndexes: file_secrets_proto_depIdxs,
		EnumInfos:         file_secrets_proto_enumTypes,
		MessageInfos:      file_secrets_proto_msgTypes,
	}.Build()
	File_secrets_proto = out.File
	file_secrets_proto_goTypes = nil
	file_secrets_proto_depIdxs = nil
}
