syntax = "proto3";

package gophkeeper.v1;

import "buf/validate/validate.proto";
import "google/protobuf/timestamp.proto";

option go_package = "./gophkeeper";

// info displayed in the list
message SecretInfo {
  enum Kind {
    KIND_UNSPECIFIED = 0;
    KIND_CREDENTIALS = 1;
    KIND_CARD = 2;
    KIND_TEXT = 3;
    KIND_RAW = 4;
  }

  string uuid = 1 [(buf.validate.field).string.uuid = true];
  string name = 2;
  Kind kind = 3;
  google.protobuf.Timestamp created = 4;
  google.protobuf.Timestamp modified = 5;
}

message Credentials {
  string login = 1;
  string password = 2;
}

message Card {
  string number = 1;
  string holder = 2;
  string expires = 3 [(buf.validate.field).string.pattern = "^(0[1-9]|1[0-2])/\\d{2}$"];
  string verification_code = 4;
}

message Text {
  string filename = 1;
  string content = 2;
}

message Raw {
  string filename = 1;
  int64 size = 2;
}

message SecretDetails {
  string description = 1;
  oneof secret {
    Credentials credentials = 2;
    Card card = 3;
    Text text = 4;
    Raw raw = 5;
  }
}

// InfoList reads secrets info to display in the list
message InfoListRequest {}

message InfoListResponse {
  repeated SecretInfo secrets_info = 1;
}

// Create creates secret with such name and details.
// Returns info about created secret
message CreateRequest {
  string name = 1;
  SecretDetails details = 2;
}

message CreateResponse {
  SecretInfo info = 1;
}

// Read reads details of the secret with such info.
// Returns FailedPrecondition error, if info is outdated, so client should call
// List and Read again
message ReadDetailsRequest {
  SecretInfo info = 1;
}

message ReadDetailsResponse {
  SecretDetails details = 1;
}

// Update updates name (from info) and details of the secret with such info
// Returns FailedPrecondition error, if info is outdated, so client should call
// List, Read, merge on client side (using any implemented strategy)
// and Update again
message UpdateRequest {
  SecretInfo info = 1;
  SecretDetails details = 2;
}

message UpdateResponse {
  google.protobuf.Timestamp modified = 1;
}

// Delete deletes secret with such info
// Returns FailedPrecondition error, if info is outdated, so client should call
// List and Delete again
message DeleteRequest {
  SecretInfo info = 1;
}

message DeleteResponse {}

// UploadRaw uploads raw file content
// Returns FailedPrecondition error, if expected_modified not matched
message UploadRawRequest {
  message Begin {
    string uuid = 1 [(buf.validate.field).string.uuid = true];
    google.protobuf.Timestamp expected_modified = 2;
  }
  oneof data {
    Begin begin = 1;
    FileChunk chunk = 2;
  }
}

message FileChunk {
  bytes content = 1;
}

message UploadRawResponse {
  google.protobuf.Timestamp modified = 1;
}

// DownloadRaw downloads raw file content
// Returns metadata in first packet and chunks in the others
message DownloadRawRequest {
  string uuid = 1;
}

message DownloadRawResponse {
  message Begin {
    string filename = 1;
    int64 size = 2;
    google.protobuf.Timestamp modified = 3;
  }
  oneof data {
    Begin begin = 1;
    FileChunk chunk = 2;
  }
}

service SecretsService {
  rpc InfoList(InfoListRequest) returns (InfoListResponse);
  rpc Create(CreateRequest) returns (CreateResponse);
  rpc ReadDetails(ReadDetailsRequest) returns (ReadDetailsResponse);
  rpc Update(UpdateRequest) returns (UpdateResponse);
  rpc Delete(DeleteRequest) returns (DeleteResponse);
  rpc UploadRaw(stream UploadRawRequest) returns (UploadRawResponse);
  rpc DownloadRaw(DownloadRawRequest) returns (stream DownloadRawResponse);
}
